### PR TITLE
Webpack 5 + favicons

### PR DESCRIPTION
**Pull request by TomTirapani**
+ Upgrade to Webpack 5: https://github.com/xh/hoist-dev-utils/issues/33
+ Remove favicons-webpack-plugin: https://github.com/xh/hoist-dev-utils/issues/30

Uses a custom plugin to replace the manifest.json generation that was bundled with favicons-webpack-plugin. Allows apps to either:
+ Have a single favicon file embedded in the html. This should be sufficient for most desktop only apps expected to run in modern browsers.
+ Include the favicon variants required for mobile "standalone" apps included in the manifest.json (from https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs). Note that this requires the developer to provide the variously sized favicons manually - I think this is a relatively straightforward, one-time operation.

### CODE REVIEW

**Comment by amcclain** [comment]
I spent a while looking at this today - eager to get it in.

Made some updates - please review when you have a chance. Note there's a commit or two on the hoist-react branch also related to removing some backwards compat stuff.

The next-up mystery for me are these newly specific chunk names - I really want to look over what we are doing here and determine what has changed and if our approach to splitting out and then including these chunks still makes sense.  Note that highlighted names are just some of the differences - you can see there are a number of files that no longer have app name in title and instead have specific HR files, etc.  (Difficult to type in a comment - look closely and compare w/current build you will see whaat I mean)

New build:
Screen Shot 2022-03-16 at 6 09 49 PM

Prev build:
Screen Shot 2022-03-16 at 6 13 54 PM

**Comment by TomTirapani** [comment]
Your changes look great Anselm! Especially nice to have the script find and include those standard favicons automatically.

Will look at the chunk names above. What tool are you using there to get the list?

Also, I noticed that after updating the `@xh/eslint-config`, we're getting loads of linter errors from hoist-react / toolbox around indentation. Will want to look at exactly what's changed there, and if we want to adjust the rules so that it settles down a bit.

**Comment by TomTirapani** [comment]
Regarding the ESLint issue:

With ESLint 8, it now reports an indentation error on any property / method that uses decorators: https://github.com/eslint/eslint/issues/15299. That's a significant part of our codebase!

Unfortunately, it sounds like the maintainers of the ESLint plugin that babel uses to handle experimental features like decorators will not have the bandwidth to fix it any time soon: https://github.com/typescript-eslint/typescript-eslint/issues/1824.

Should we roll back the `@xh/eslint-config` release? Was there an important motivation for upgrading to ESLint 8, or was it just a case of wanting to stay current?

**Comment by TomTirapani** [comment]
Okay - I spent far too long on this, but I was able to significantly simplify our chunk naming & inclusion logic. Now, we've taken control of the naming to ensure that chunks are again named according to the delimited list of entry points that use them. Secondly, I've switch the logic to focus on `inclusion` rather than `exclusion`, which hopefully should be simpler to understand.

**Comment by amcclain** [comment]
> With ESLint 8, it now reports an indentation error on any property / method that uses decorators: [eslint/eslint#15299](https://github.com/eslint/eslint/issues/15299). That's a significant part of our codebase!

This workaround appears to clear up this issue and all the warnings it generates. I believe it effectively disables indent checking on all class properties (or something like that), but I am not too worried about that.

https://github.com/xh/eslint-config/commit/689829a38fd0bb353b35bc07e775b3ee20a81cee

**Pull request merged**
